<?php
return array(
	'app'=>'account',
	'name'=>'用户',
	'description'=>'用户注册，登录，权限管理等',
	'version'=>'1.0.0',
	'author'=>'别小俊',
	'date'=>'2016.06.23',
	'icon'=>'icon-user',
	'special'=>false,
	'options'=>array(
		array(
			'title'=>'全部用户',
			'admin'=>'admin_user.php'
		),
		array(
			'title'=>'用户黑名单',
			'admin'=>'admin_user_blacklist.php'
		)
	),
	'route'=>array(
		'/^account\/([a-z0-9_]+)$/'=>'account/:1'
	)
);